name: Package Application with Pyinstaller

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@tkinter
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: txn-export
        path: src/dist/linux